### ISSUE TITLE
inconsistent parentheses in option items

### ISSUE THREAD

**Issue by odanoburu** [own-pt/oab-exams#2]
what is the correct way to mark option letters?

is it `A)` or `(A)`?

in https://github.com/own-pt/oab-exams/blob/master/OAB/raw/2010-official-1.txt  we have the former, while in https://github.com/own-pt/oab-exams/blob/master/OAB/raw/2010-official-2.txt we have the latter. 

this regex snippet can change it from the former to the later:

```cl
(cl-ppcre:regex-replace-all "\\((?=[A-D](\\)|:CORRECT\\)))" *oab-exam* "")
```
ps: there is a significant number of files in both formats.

**Comment by pdelfino** [comment]
Hi Bruno,
You found a typo, thanks. According to the readme of the raw files, @arademaker and I defined the convention as this model https://github.com/own-pt/oab-exams/blob/master/OAB/raw/2010-official-1.txt.

I will fix this today (max tomorrow). I think a simple script may handle the problem, eliminatig ( before alternatives. The conventions were inserted manually, other typos may have occured.

**Comment by arademaker** [comment]
@odanoburu obrigado. Resolvi fácil com um replace de expressão regular no Emacs.  Mas o problema maior é no arquivo 2010-official-2.txt que tem várias palavras quebradas!
