### ISSUE TITLE
adição de novas provas no repo

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#29]
Tive problemas com java e software da apache. Usei pdf->html->txt. Conversão parece ser muito bem sucedida. Ver mais comentários sobre isso no commit 8bd4f7c

**Comment by arademaker** [comment]
@pdelfino https://tika.apache.org não foi feito pela Unicamp! Talvez tenha um mirror na Unicamp para download, mas o tika é um projeto independente da Unicamp. De qq modo, melhor documentar aqui no issue como vc converteu os files. Usar um site que amanhã pode não estar disponível pode tornar o processo não reproduzível.

**Comment by arademaker** [comment]
Podemos fechar este issue considerando que as novas provas foram já adicionadas ao repo?

**Comment by pdelfino** [comment]
Beleza. Eu usei esse site: http://www.pdfonline.com/convert-pdf-to-html/

Mas eu tive esse _insight_ por conta de um comentário no stackoverflow. Um usuário sugeriu converter de pdf para html como passo intermediário na conversão pdf -> (html) -> txt. A ferramenta não parece ter sido o "pulo do gato", foi mais a abordagem.
