### ISSUE TITLE
Como "taguear" tutela coletiva

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#30]
Apareceu uma questão de tutela. Fiquei na dúvida em como classificar. Guilherme sugeriu no telegram seguir a classificação da FGV projetos explicitado nos relatórios "OAB em números". Ver mais comentários no commit 7e89f1a

**Comment by arademaker** [comment]
os comentários dos commits devem ser mais objetivos e curtos. discussões mais longas ficam em issues. Em tempo, no comentário do commit indicado, não me pareceu haver qq conclusão, certo?

**Comment by pdelfino** [comment]
Beleza! Eu classifiquei como civil-procedure. Vou olhar relatório do OAB em números para ver como eles tratam tutela coletiva de Direitos.

**Comment by pdelfino** [comment]
Até hoje, a instituição que ficou responsável por quase todos os exames unificados (a FGV projetos) fez 3 relatórios "Exame da Ordem em Números": [primeiro](http://fgvprojetos.fgv.br/sites/fgvprojetos.fgv.br/files/exame_de_ordem_em_numeros.pdf), [segundo](http://fgvprojetos.fgv.br/sites/fgvprojetos.fgv.br/files/relatorio_2_edicao_final.pdf) e [terceiro](http://fgvprojetos.fgv.br/sites/fgvprojetos.fgv.br/files/oab_3_edicao_v4_web_espelhado.pdf).

Os termos "tutela coletiva", "direitos difusos" não aparecem em nenhum dos pdfs. Na pag 11 do primeiro pdf é possível ver a classificação usada das áreas. **A nossa classificação está convergente com a classificação temática da banca,** exceto o fato de usarmos palavras em inglês.

Esses relatórios me parecem um material bem interessante. Vou inseri-los no repositório num diretório _reports_.
