### ISSUE TITLE
Confirmar originalidade dos simulados

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#31]
Checar com os responsáveis pelos simulados na Direito Rio a origem das questões. Se vierem de provas de anos anteriores, deletar do repositório.

**Comment by pdelfino** [comment]
Perguntei para os funcionários da Direito Rio, eles me disseram que os simulados são criações dos professores responsáveis pela preparação para as provas e **não** são questões de anos anteriores.

Já aconteceu de questões de anos anteriores serem usadas, por exemplo, quando um professor não enviou a tempo as suas questões, mas essa não é a regra. Testei 5 questões aleatórias de 5 provas aleatórias, jogando no google, para ver se o google direcionava para uma questão que já caiu em algum exame oficial. O resultado foi que todas as 5 questões não eram de provas anteriores do exame oficial.

**Portanto, os simulados são originais, complementam a base de dados e vão ser mantidos no repo.**

É preciso organizar as provas (estão com erros na indicação de ano), converter de docx para txt, limpar os arquivos e inserir os marcadores. Temos a disposição, atualmente, mais simulados do que exames oficiais.

**Comment by arademaker** [comment]
@pdelfino melhor então abrir outro issue para tratar da conversão dos docx para o mesmo formato das provas.
