### ISSUE TITLE
tag das áreas temáticas de cada questão nas provas

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#33]
No início da unificação do Exame, a ordem das questões variava na aplicação da prova. Nos exames mais recentes, parece que um padrão de ordenação temático vem se repetindo.

Num commit de ontem, sobre o segundo exame unificado (2010-2), comentei que ética não foi a primeira matéria abordada:  7e89f1a. No II Exame Unificado, a primeira matéria foi constitucional.

Na terceira aplicação do exame unificado (2010-3), novamente, houve uma mudança na ordem temática das questões: direito administrativo foi a primeira questão abordada. Outro ponto interessante dessa prova é a questão 21, uma pergunta de constitucional, em meio a questões de processo civil, falando sobre mandado de segurança coletivo (um tipo de ação, ações normalmente são abordadas em direito processual civil/penal). Ver commit: 08fe4f4

Importante lembrar que o primeiro exame unificado foi feito pela instituição CESPE. Do 2° exame unificado em diante, a instituição responsável foi a FGV PROJETOS.

**Comment by pdelfino** [comment]
Sobre o IV Exame Unificado da OAB, cabe destacar:
- começou com ética
- teve 12 questões de ética
- teve 2 questões de direito internacional no meio de direito constitucional. Isso reflete um pouco um problema de epistemologia. Para alguns, Direito internacional está, como conhecimento, dentro de Direito constitucional.

**Comment by pdelfino** [comment]
Sobre o V Exame Unificado da OAB, cabe destacar:

- começou com ética
- teve 12 questões de ética (mais para frente, nas provas mais recentes, parece ter estabilizado em 10 questões por prova)
- teve 2 questões bem claras de Direitos Humanos. Talvez, elas poderiam ser classificadas como questões de Direito Internacional, no entanto, o enunciado fazia clara referência a direitos humanos. Ver questões 13 e 14.
-houve apenas 7 questões de constitucional. O número me parece pequeno. Nas provas mais recentes o padrão parece ser de 10 questões.

Ver mais detalhes no commit 1956692

**Comment by arademaker** [comment]
@pdelfino issues são coisas a serem feitas, com inicio, meio e fim. Não são comentários gerais. Qual é este issue? Estas observações todas estão no contexto de qual problema que está sendo resolvido?  Anotação das áreas nas questões?

**Comment by arademaker** [comment]
relacionado com #29 . Deve ser feito, na verdade, depois de fechado o #29. Também depende de #31 dado que se os simulados forem confirmados serem seleções de questões de provas anteriores, então eles poderão ser removidos do repo. Caso contrário, vamos precisar tratar os simulados como as provas criando arquivos de mesmo formato e com as tags de áreas.

**Comment by pdelfino** [comment]
Beleza, professor. Esse issue foi mais barbeiragem minha rsrs. Peço desculpas. Nunca tinha usado essa funcionalidade do github. Eu tava usando como um agregador de comentários e não uma "lista de tarefas e problemas a serem resolvidos". Vou fechar isso aqui. Já resolvi o #29. Vou resolver o #31 amanhã, aparentemente, os simulados mais antigos são originais (feitos por professores da direito rio) e os mais recentes são só aglomerados de questões de provas de anos anteriores do exame oficial.
