### ISSUE TITLE
problema no linker do LeXML Brasil para converter DOCX -> XML do texto inteiro da Constituição

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#34]
No commit ac13abe, eu tentei adicionar a constituição da república no nosso repositório. Fiz o seguinte:

1 -  Abri no site do planalto, copiei o texto e fiz um arquivo docx;

2 - Adaptei o cabeçalho para o linker aceitar como "projeto de lei";

3 - Submeti no [linker](http://linker.lexml.gov.br/lexml-parser/parse/static/simulador/simulador.html). Ele não processou o arquivo do docx com a constituição inteira, desconfiei que fosse por conta do tamanho do arquivo. A constituição é bem maior do que as leis que a gente já tem no repositório

4 - De modo a validar minha hipótese, criei um arquivo constituição-input-linker-sample, com uma amostra de poucos artigos. Aí funcionou.

Qual seria a melhor forma de resolver isso? Falar com o pessoal do LexML? Decompor a constituição em várias pequenas partes e ir submetendo no liker ao poucos para depois ajuntar tudo?

**Comment by odanoburu** [comment]
talvez interesse: https://github.com/lexml/lexml-parser-projeto-lei/issues/2

**Comment by arademaker** [comment]
@pdelfino certamente vamos precisar, depois de ler este ponteiro do @odanoburu, falar com o pessoal do LexML novamente.

**Comment by pdelfino** [comment]
@arademaker e @odanoburu , abri uma issue no LexML [sobre isso.](https://github.com/lexml/lexml-parser-projeto-lei/issues/8). Nessa issue eu citei uma novidade.

Eu fiz uma segunda tentativa, retirando a formatação do texto ao copiar o texto da constituição do site do planalto e colar no word. A conversão para xml parece ter sido bem sucedida. Mas falta checar. [Deem uma olhada aqui](https://github.com/own-pt/oab-exams/blob/master/lexml/const-2nd-try/constituicao-no-format.xml ).
