### ISSUE TITLE
análise de fundamento das questões de constitucional

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#38]
Construir um arquivo YAML com a análise do fundamento de 30 questões de constitucional:
 
tickar o check list depois de verifciar a sintaxe do YAML em http://www.yamllint.com/

- [x] 1

- [x] 2

- [x] 3

- [x] 4

- [x] 5

- [x] 6

- [x] 7

- [x] 8

- [x] 9

- [x] 10

- [x] 11

- [x] 12

- [x] 13

- [x] 14

- [x] 15

- [x] 16

- [x] 17

- [x] 18

- [x] 19

- [x] 20

- [x] 21

- [x] 22

- [x] 23

- [x] 24

- [x] 25

- [x] 26

- [x] 27

- [x] 28

- [x] 29

- [x] 30

**Comment by odanoburu** [comment]
@pdelfino vc poderia tb pular a etapa do .tex e fazer direto o arquivo tipo o [justify](https://github.com/own-pt/oab-exams/blob/master/doc/justify.txt). vc acha que faz sentido? se for útil o .tex pra vc se organizar, by all means do it!

**Comment by arademaker** [comment]
@pdelfino acho que podemos evoluir o justify para um json ou YAML que permita fazermos o link entre `(questao,prova) -> (artigo,norma)` e também ter um campo livre de justificativa/comentários.

**Comment by odanoburu** [comment]
concordo que o formato atual é muito barebones... mas já tem um campo de comentário sim, só que com delimitador `\t` é difícil de ver, pq o github não indenta direito...

acho que YAML é mais fácil de criar na mão!

**Comment by pdelfino** [comment]
Beleza, boa! Professor @arademaker  falou JSON ou YAML.

Mas pelo comentário do @odanoburu, vou fazer em YAML, então, beleza?

Começo isso amanhã. Esse template vai funcionar para YAML, certo?

---
questao: 
prova: 
artigo:
norma:
comment:
---

Se eu for fazer:

```
questao: "12"
prova:  "2016-16"
artigo: "14"
norma: "lei 8096"
comment: "placeholder placeholder"

```
1) Eu coloco em " " todos os valores?

2) O que vcs acham de colocar em inglês?

3) O que vcs acham de ordenar as "keys" em generalidade, primeiro o exame, depois a questão, primeiro a norma, depois o artigo, depois o inciso ou parágrafo?

4) O que vcs acham de colocar um espaço para a localização da resposta dentro do artigo?
 
Dentro de um artigo, a resposta pode estar em um dos incisos, em um dos parágrafos, em uma alínea dentro de um inciso ou no parágrafo único.

5) Na lei, os incisos são numerados com número romano. Mas, se não me engano, isso pode ser ruim para processar o texto. O que vcs acham? Mantem a convenção da prova ou muda o padrão?

Minha sugestão seria:

```
exam:  "2016-16"
question: "12"
norm: "lei 8960"
article: "14"
subsection: "IV"
comment: "placeholder placeholder"

```

**Comment by arademaker** [comment]
Pedro , veja página Wikipedia sobre yaml , vc não precisa das aspas não. E o template generaliza fácil para casos onde mais de um artigo responde a pergunta. Sim eu mesmo ao colocar o template sugeri yaml

**Comment by arademaker** [comment]
Faça alguns casos para podermos na próxima reunião discutir e refinar. A ordem das chaves é irrelevante. Não entendi o subsection. Talvez possamos usar os URN que LexML prevê como identificadores dos itens nas normas

**Comment by arademaker** [comment]
Finalmente não esqueça que teremos que colocar no mesmo formato as outras 30 de ética

**Comment by pdelfino** [comment]
OK, vou criar outro issue para controlar a reformatação das 30 questões de ética em YAML.

Subsection seria para especificar melhor o fundamento de uma resposta. Ficar apenas no artigo é pouco descritivo. Veja o[ artigo 7 da Lei 8906](http://www.planalto.gov.br/ccivil_03/leis/L8906.htm)

Ele era a resposta de várias questões. No entanto, ele é gigante, tem vários incisos e parágrafos (chamei essa subdivisão do artigo de subsection).

Essa key ia deixar mais descritiva o fundamento da resposta.

Beleza, vou olhar o wikipedia de YAML. Eu tinha visto sobre YAML esse [guia no github](https://github.com/Animosity/CraftIRC/wiki/Complete-idiot%27s-introduction-to-yaml). Em determinado momento o cara disse:

> "So even though quotes are optional, using them is highly recommended."

**Comment by pdelfino** [comment]
Comecei a fazer. Em uma das questões tinham dois artigos. Fiz da forma abaixo:
https://github.com/own-pt/oab-exams/blob/master/doc/justify-const.yaml

Se vcs tiverem sugestões será bem-vindo =)

**Comment by arademaker** [comment]
Fiz umas mudanças lá. mas talvez discutindo na semana que vem e com mais exemplos ainda possamos melhorar. Em especial, acho que qq item é referencial como uma URN no LexML. Então mesmo um parágrafo ou inciso podem ter uma URN, mas posso estar enganado.  Se isto for o caso, podemos usar apenas URNs.

**Comment by odanoburu** [comment]
acho que todo parágrafo e inciso tem URN sim, mas e quando a questão se fundamentar em várias coisas sub-artigos? vamos ter de colocar as URNs de todas, que terão o mesmo prefixo? (é possível, mas será que tem solução mais elegante?)

**Comment by pdelfino** [comment]
Professor @arademaker ,

Eu vi as mudanças que vc fez. No entanto, estou com uma dúvida. Aparentemente, a forma como vc usou o `---`  atrapalha o parsing e a validação da sintaxe do Yaml.

Estou com essa dúvida por conta das ferramentas de YAML que estou usando para checar a sintaxe e para ver como ficar a conversão YAML -> JSON.  [Essa é a sua versão do arquivo YAML.](https://raw.githubusercontent.com/own-pt/oab-exams/292866878d52c574aa99610745ff8829101e75be/doc/justify-const.yaml)

Se eu submeter a sua versão do yaml [nesse parser aqui](yaml-online-parser.appspot.com ) ocorre o erro:
```
ERROR:

expected a single document in the stream
  in "<unicode string>", line 2, column 1:
    exam: 2010-01
    ^
but found another document
  in "<unicode string>", line 13, column 1:
    ---
```
Além disso, se eu verificar a sintaxe do seu arquivo no [YAMLlint](http://www.yamllint.com/) , depois da verificação, o "interpretador" considera apenas a primeira questão analisada e descarta as outras! Ele considera apenas a que está entre a primeira dupla de `---`

De acordo com a documentação do YAML:

_

> There’s another small quirk to YAML. All YAML files  can optionally begin with --- and end with .... This is part of the YAML format and indicates the start and end of a document.

_

Acho que o interpretador vê o segundo `---` e considera que está iniciando outro arquivo, sendo que está tudo no mesmo. Acho que pode ser isso que está gerando a confusão nessas ferramentas.

Enfim, isso é mais uma dúvida sobre o que está acontecendo do que apontar um possível erro. Não sei se estou interpretando mal ou se as "ferramentas" que estou usando para validar a sintaxe estão erradas (pode ser isso também).

Vc e o Bruno tem mais experiência com o YAML. Queria ouvir de vcs porque isso está acontecendo e se tem algum problema separar as questões com `---`

**Comment by pdelfino** [comment]
Conversei com o @arademaker por email. Apenas para registrar aqui os principais tópicos da conversa (e checar se não entendi errado):

1 - YAML é um formato com uma funcionalidade multidocumento, um mesmo arquivo pode ter varios documentos. Os —- não serão problemáticos para o parser que pretendemos usar para ler esses dados, apesar de terem sido mal interpretados nas ferramentas que eu usei. 

2 - Representar ou não a subseção do artigo, que pode ser o caput, um inciso, um parágrafo ou o paragrafo unico continua em aberto. A certeza que temos é que ou usaremos (i) a urn sendo o último identificar o artigo ou (ii) usaremos a urn sendo o último marcador a subseção. De qualquer forma, o comentário continua sendo um espaço livre e pode ser verboso, se for necessário.

**Comment by pdelfino** [comment]
@arademaker , terminei. [Aqui está](https://github.com/own-pt/oab-exams/blob/master/doc/justify-ethics.yaml). Estou inseguro se fiz alguma bobagem no yaml.
