### ISSUE TITLE
adicionar o último exame (edição XXIV), aplicado no final de novembro

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#42]

**Comment by pdelfino** [comment]
Adicionei o [pdf original da prova,](https://github.com/own-pt/oab-exams/blob/master/OAB/pdf/2017-official-24.pdf) o [pdf do gabarito](https://github.com/own-pt/oab-exams/blob/master/OAB/pdf/answer-sheet/2017-official-24-as.pdf) e o [arquivo processável em txt da prova.](https://github.com/own-pt/oab-exams/blob/master/OAB/raw/2017-24.txt)
Falta inserir os marcadores, em especial, o gabarito no arquivo txt. Pretendo construir um código para fazer esse processo de forma mais automática, sobretudo a limpeza do arquivo e a inserção do gabarito em cada questão com o marcador  `:CORRECT)`.

**Comment by arademaker** [comment]
@pdelfino não acho que vc irá poupar muito tempo com este código. Novamente, acho que temos outras prioridades.

**Comment by pdelfino** [comment]
Beleza, @arademaker . Acho que, pelo menos, o gabarito me parece factível e acho que pouparia. Só coloquei como comentários. Estou fazendo pro dia 5 as tarefas que a gente combinou no email!
