### ISSUE TITLE
adicionar lei 9868 em formato XML

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#45]
Em uma das questões selecionadas para o golden de constitucional, a resposta estava na lei sobre ADI, Lei 9868. Estou me referindo à questão 13 do primeiro exame unificado, feito em 2010.

**Comment by pdelfino** [comment]
Dispositivo: http://www.planalto.gov.br/ccivil_03/Leis/L9868.htm
No LexML Brasil: http://www.lexml.gov.br/urn/urn:lex:br:federal:lei:1999-11-10;9868

**Comment by arademaker** [comment]
Basta sabermos o link do lexml , dele chegamos ao documento certo ?

**Comment by pdelfino** [comment]
Sim. No limite, seria só jogar no Google. Como vc disse que isso poderia ser complicado para quem não tem background knowledge, achei melhor colocar nos dois.

Alguém pode entrar no link de lexML e, ao invés, de clicar na versão **atual**  da lei, acabar clicando na versão **original** da lei. Assim, a pessoa estaria consultando uma versão desatualizada.

Buscando pelo Google é até mais difícil do cara confundir original e atual... Pelo LexML me parece factível. Por isso, coloquei os dois...

**Comment by pdelfino** [comment]
feito  98c6e46e0b9dbcdabe779e66ab4f3d3b80dda210
