### ISSUE TITLE
adicionar lei  11417 de 2006

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#47]
Essa lei é o fundamento da questão 18 do V exame unificado (2011).

**Comment by pdelfino** [comment]
Dispositivo: http://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11417.htm
No LexML Brasil: http://www.lexml.gov.br/urn/urn:lex:br:federal:lei:2006-12-19;11417

Um ponto curioso: essa lei é bem curtinha!

**Comment by arademaker** [comment]
Sempre que o documento estiver indexado pelo lexml , basta o link do lexml certo ?
