### ISSUE TITLE
adicionar licença para o projeto oab-exams

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#48]
site recomendado pelo github: https://choosealicense.com/

**Comment by pdelfino** [comment]
adicionei

https://github.com/own-pt/oab-exams/blob/master/LICENSE.txt

Tomei a liberdade de fazer uma alteração de:

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software")

Mudei para:

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software**, data set** and associated documentation files (the "Software")

Se vcs @odanoburu , @arademaker , acharem ruim, eu mudo!

**Comment by arademaker** [comment]
Acho que deveríamos dizer que os dados originais não são nossos e onde foram obtidos. O que estamos provendo são os dados tratados de forma estruturada.
