### ISSUE TITLE
adicionar súmula vinculante 683

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#49]
Essa súmula é fundamental para responder a questão 16 do XXII exame unificado (2017).

Urn:
urn:lex:br:supremo.tribunal.federal:sumula:2003-09-24;683

**Comment by pdelfino** [comment]
Observação, essa súmula é de 2003 e foi cobrada numa prova de 2017!

**Comment by arademaker** [comment]
http://www.stf.jus.br/portal/jurisprudencia/menuSumarioSumulas.asp?sumula=2413

**Comment by pdelfino** [comment]
Feito em f8be073acdab53cb66ff7d2f5653c1210e618627

Não sei se o XML gerado está adequado. Aqui está [o arquivo](https://github.com/own-pt/oab-exams/blob/master/lexml/constitutional-system/summary-683/683.xml).

 Essa **norma** que foi relevante para o exame tem a peculiaridade de ser uma súmula do STF. 

Explicação: _súmula é a interpretação pacífica ou majoritária adotada por um Tribunal a respeito de um tema específico, a partir do julgamento de diversos casos análogos, com a finalidade de promover a uniformidade entre as decisões._

**Comment by arademaker** [comment]
O que vc quer dizer com o XML gerado não estar adequado ???

Alexandre

**Comment by pdelfino** [comment]
As etiquetas estão estranhas.

O conteúdo da súmula está dentro da etiqueta "ementa"

Ementa normalemnte é reservado para um espécie de "resumo" do que se trata
a lei

Em 6 de março de 2018 19:50, Alexandre Rademaker <notifications@github.com>
escreveu:

> O que vc quer dizer com o XML gerado não estar adequado ???
>
> Alexandre
> Sent from my iPhone
>

**Comment by arademaker** [comment]
Isto pode ser um desafio mesmo . O parser pode produzir um xml válido , well formed em relação a um dtd e mesmo assim com o conteúdo inadequado na estrutura. Vamos amanhã conversar como podemos lidar com isso. Antes precisamos ver se temos casos assim .. entender como o parser deles funciona também é essencial
