### ISSUE TITLE
conversão problemática das provas (pdf -> txt)

### ISSUE THREAD

**Issue by arademaker** [own-pt/oab-exams#5]
Alguns arquivos apresentaram problemas sérios de perda de palavras e pedaços de frases. Vide c6e976f0191feedb753d213e3b1386cc92a42e01 por exemplo. Os arquivos mais afetados parecem ser 

- [x]  2014-official-15.txt
- [x] 2015-official-16.txt

mas precisamos tentar verificar no futuro melhor o que pode ter sido perdido.

**Comment by arademaker** [comment]
@pdelfino importante não esquecer deste isso também.

**Comment by pdelfino** [comment]
Questão 14 do 14 exame unificado, está com problema, parte do texto foi perdido.

**Comment by pdelfino** [comment]
Feito em 4471082f3d35291dc996f4ecfbc21ee732973f6b e 1a06fe70f9867a4d49763e0b461fc8818957b5f2

O segundo commit está mais rico no processo utilizado para consertar os arquivos corrompidos.
