### ISSUE TITLE
decompor a constituição em ADCT e em texto normal, adicionando as duas partes ao repo

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#53]
Essa foi a recomendação do João na issue que abri no LexML Brasil.

**Comment by arademaker** [comment]
Não entendi o problema e sugestão. Pode colocar aqui o link para o issue onde João comentou isso? Qual o contexto ? Por que um issue separado para isso ? Não seria parte do issue já aberto sobre completar dados de legislações ?

**Comment by pdelfino** [comment]
Oi professor,

A constituição tem uma parte chamada ADCT (atos das disposições constitucionais transitórias). Juridicamente, isso é parte da norma constituição. No entanto, para o parser, o ADCT é uma norma separada. Por isso, estava quebrando submeter a constituição inteira no parser do Lexml Brasil! Tem que decompor em duas normas e submeter separadamente.

Abri uma nova issue e fechei a anterior. A anterior era sobre o "problema no linker+parser". Na verdade, não é um problema, a constituição tem esse detalhe e acaba sendo uma limitação, mas não é um bug. Na constituição tem dois artigos primeiros, o artigo primeiro da constituição mesmo e o artigo primeiro do ADCT (uma espécie de apêndice importante). Isso causava o bug. Que eu saiba a constituição é a única norma que tem dois artigos primeiros...

Abri uma issue separada porque é um novo problema, uma nova tarefa: fazer o upload da constituição decompondo em duas partes. Esse é o issue em que o João respondeu:

https://github.com/lexml/lexml-parser-projeto-lei/issues/8




https://github.com/lexml/lexml-parser-projeto-lei/issues/8

**Comment by pdelfino** [comment]
http://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm 

A parte do ADCT começa em _ATO DAS DISPOSIÇÕES CONSTITUCIONAIS TRANSITÓRIAS_

**Comment by arademaker** [comment]
Decompor a constituição é necessário apenas para rodar o parser , mas o final deve ser um xml apenas certo ?

**Comment by pdelfino** [comment]
Sim

**Comment by pdelfino** [comment]
A constituição, a parte com o texto 'permanente', foi adicionada.
Falta a parte com os atos de disposições constitucionais transitórias (ADCT).

**Comment by pdelfino** [comment]
feito em  (adct) 4fa2bacb0456d512a791afe975377b0d98eabbae e (outra parte da constituição) bbceb26acd6bd4096b15594720871f8aff5dc3df

Ainda é necessário unir o XML do ADCT e o XML da Constituição. Não sei a melhor forma de fazer isso @arademaker . O LexML Brasil trata como duas normas diferentes no seu padrão de etiquetas.

Até onde eu sei, a constituição é a única norma que tem dois artigos primeiro.

**Comment by odanoburu** [comment]
acho que é melhor mantermos separado. se juntarmos teremos um documento não válido sob o schema LeXML..

algum motivo pra juntar além da praticidade?  não consegui pensar aqui..

**Comment by pdelfino** [comment]
Eu me expressei muito mal. Escrevi rápido. Ficou ruim.

Só quis dizer que tem um argumento a mais que o Bruno não percebeu.

Juntar os dois xml tem dois benefícios:

(i) praticidade

(ii) respeitar a natureza da norma oficial, do dado original. Na norma
oficial, na constituição brasileira, os ADCT e o restante da constituição
estão na mesma norma, elas não são duas normas separadas. Se a gente seguir
o LexML Brasil e tratar como duas normas diferentes seria algo
"artificial", seria alterar o dado original.





Em 7 de março de 2018 20:41, Alexandre Rademaker <notifications@github.com>
escreveu:

> Nao entendi se o argumento do Pedro é para juntar ou separar ...
>
> Tambem sem estudar mais a fundo o dtd do lexml e entender este caso da
> constituição e estas ADCT, não sei dizer se o formato lexml contemplaria
> isto como um único documento ou não.
>
> Sent from my iPhone
>
