### ISSUE TITLE
editar justify-ethics.yaml com base nos aprimoramentos de justify-const.yaml

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#56]
Os aprimoramentos foram, especialmente, no sentido de indicar onde especificamente, dentro do artigo (em qual subsection), está a resposta. O "pulo do gato" é não inventar a roda e usar a convenção desenvolvida pelo LexML Brasil - mais no commit eb887f16a6622ec3e7eb080bd684538c51c5e1c6

**Comment by arademaker** [comment]
Sempre bom indicar os commits que vc está fazendo relacionados à cada issue.

**Comment by pdelfino** [comment]
Certo, não sabia dessa boa prática, peço desculpas.

Esse é o commit eb887f16a6622ec3e7eb080bd684538c51c5e1c6

**Comment by pdelfino** [comment]
Done, ver commit 133d4ff0c24ca04e23747ba8686a8d13cecaf10b
