### ISSUE TITLE
erro no documento original do simulado da oab

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#75]
Na questão 16 da prova 2013-15 do simulado da OAB elaborado pela FGV DIREITO RIO existe o seguinte erro:

![screenshot from 2018-02-10 10-57-52](https://user-images.githubusercontent.com/7698207/36062334-927c6088-0e51-11e8-8a08-bd15e30d942b.png)

Não aparece alternativa C, com duas alternativas D. Claramente, um erro de digitação.

Curiosamente, o gabarito oficial aponta como resposta a alternativa D:

![screenshot from 2018-02-10 10-58-54](https://user-images.githubusercontent.com/7698207/36062339-a6c8fa38-0e51-11e8-962f-ec405b4b8b61.png)

A resposta é:
    A procuradoria-geral da Fazenda Nacional integra a Advocacia-Geral da União.

Fundamento: Lei Complementar 73, de 1993, artigo 2 e parágrafo primeiro.

Quando estávamos fazendo a limpeza e formatação dos dados de official/raw, encontramos erros na prova oficial. No caso, era um erro de português ou uma palavra faltando em determinada frase.
Naquela ocasião, optamos por manter o arquivo raw fiel ao original, mesmo que com o erro.

Nesse caso, o que devemos fazer @arademaker?

Sugiro corrigir o erro e deixar o arquivo raw assim:

```
---
ENUM Questão 16

AREA  


16. A respeito das funções essenciais à justiça, assinale a opção correta.


OPTIONS 

A) A CF autoriza o exercício de atividade político-partidária pelos membros do MP.

B) A inviolabilidade do advogado, por seus atos e manifestações, é absoluta.

C) A unidade, a indivisibilidade e a subordinação técnica são princípios institucionais do Ministério Público (MP).

D:CORRECT) A procuradoria-geral da Fazenda Nacional integra a Advocacia-Geral da União. 
```

**Comment by arademaker** [comment]
@pdelfino pela sua descrição:

> Quando estávamos fazendo a limpeza e formatação dos dados de official/raw, encontramos erros na prova oficial. No caso, era um erro de português ou uma palavra faltando em determinada frase.
Naquela ocasião, optamos por manter o arquivo raw fiel ao original, mesmo que com o erro.

não sabemos exatamente qual foi este erro e onde ele está, certo? Isto é um problema. Acho que é muito importante não deixarmos passar estes errors. Certamente estes erros vão atrapalhar o processamento e precisam ser tratados, por outro lado, temos que ter a 'provenance' dos dados para robustes, mostrar que nossos dados são fiéis aos originais e sabemos onde e como alteramos e o motivo.

Temos várias alternativas, uma idéia inicial seria, editar, corrigindo mas documentar em um arquivo ERRATA no root do repo exatamente o que alteramos e apontando o commit onde a alteração foi feita. Ou podemos ter um issue para isso associando exatamente os commits onde as edições foram feitas assim um diff do commit a pessoa saberia como era o dado original e o que foi feito.

**Comment by pdelfino** [comment]
Oi professor,

Fiz o arquivo errata https://github.com/own-pt/oab-exams/blob/master/errata.txt

Fiz o commit alterando o dado original, commit id 608f2352ca32b9027445bbec6eb43c91d70b9f16

Sobre **"não sabemos exatamente qual foi este erro e onde ele está, certo? Isto é um problema. "**

Tentei achar. Não consegui, provavelmente falamos disso em alguma conversa por email. Era um erro bem simples. Se minha memória não falha, estava faltando uma preposição como um "de" em alguma frase de exame oficial. Optamos por seguir fiel ao exame oficial.

Depois disso, posso fechar a issue?
