### ISSUE TITLE
inserir gabarito exame oficial 

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#80]
Exames sem gabarito indicado:

- [x] 21

- [x] 22

- [x] 23

- [x] 24

**Comment by arademaker** [comment]
Termina os exames oficiais antes dos simulados !!!

Sent from my iPhone

**Comment by pdelfino** [comment]
ok
já encerrei por hoje, amanhã cedo pego os exames oficiais

2018-02-28 19:22 GMT-03:00 Alexandre Rademaker <notifications@github.com>:

**Comment by arademaker** [comment]
o mais importante é terminarmos os oficiais antes e as leis, em segundo prioridade estão os simulados.
