### ISSUE TITLE
checar até que nível de detalhe URN chega

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#81]
Jefferson ficou de fazer isso para hoje: 01/03/2018

**Comment by odanoburu** [comment]
estou por fora, mas deve ter aqui http://projeto.lexml.gov.br/documentacao/Parte-2-LexML-URN.pdf

**Comment by pdelfino** [comment]
Jefferson mostrou. Esse commit id já mostra isso: 191a6fe4a67d6cd7d85e665d9a044acc453bcfda
